# hold-out

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn .model_selection import train_test_split
# レストランでどれくらいのチップを払うか(データセット）
df = sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
y_col = 'tip'
X = df.drop(columns=[y_col])
# '数値'と'カテゴリ'を分ける。total_billとsizeのデータフレームを取り出し、カラム部分をリスト化する。
# 目的：標準化のために数値カラムのリストを取得
numeric_cols = X.select_dtypes(include=np.number).columns.to_list()

In [5]:
numeric_cols

['total_bill', 'size']

In [6]:
# ダミー変数作成(one hot エンコーディング） ※ダミー変数に変換すると数値化する(uint8)
X = pd.get_dummies(X, drop_first=True)
X

total_bill  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  \
0         16.99     2           1          1        0        0        1   
1         10.34     3           0          1        0        0        1   
2         21.01     3           0          1        0        0        1   
3         23.68     2           0          1        0        0        1   
4         24.59     4           1          1        0        0        1   
..          ...   ...         ...        ...      ...      ...      ...   
239       29.03     3           0          1        0        1        0   
240       27.18     2           1          0        0        1        0   
241       22.67     2           0          0        0        1        0   
242       17.82     2           0          1        0        1        0   
243       18.78     2           1          1        0        0        0   

     time_Dinner  
0              1  
1              1  
2              1  
3              1  
4              1  
..           ...  
239            1  
240            1  
241            1  
242            1  
243            1  

[244 rows x 8 columns]

In [7]:
y = df[y_col]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
# trainデータとtestデータの数確認
print(len(X_train))
print(len(y_test))

170
74


In [9]:
# 標準化
# 標準化はデータ分割の後に実施する
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = X_train.copy()
# 数字のカラムのみに対して標準化
X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled = X_test.copy()
# 既に学習データでfitされているので、テストデータでfitはしない(間違えた数式になる)。汎化能力を評価するための信頼性の低下につながる
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [10]:
# 線形モデル学習
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train)
# 標準化された値で予測
y_pred = model.predict(X_test_scaled)

In [11]:
y_pred

array([2.82249035, 2.97504474, 2.8260184 , 1.38113692, 3.15154584,
       1.72121268, 2.48332645, 3.03579004, 2.75176346, 4.52560955,
       3.1133346 , 3.14781575, 2.33198109, 2.11518372, 2.93262778,
       4.27846609, 1.83157994, 2.26626275, 2.31085596, 3.24382161,
       3.81889336, 2.85616455, 2.42949782, 2.42039736, 2.20253234,
       2.42509643, 2.81777778, 4.70274951, 3.81268552, 2.38673795,
       2.29194112, 2.20803273, 2.45503466, 1.7743294 , 2.71663745,
       2.22913684, 2.72146912, 2.01205852, 5.85346207, 3.49435578,
       2.26246168, 2.20347519, 2.50905642, 4.41646769, 1.97212663,
       2.78445294, 2.65274212, 3.01652357, 2.73423023, 3.95761528,
       3.9498931 , 2.53992971, 2.71758399, 6.35620823, 1.7434279 ,
       2.33450139, 4.23562521, 3.29319236, 2.41114285, 2.20345847,
       3.72455103, 2.29099827, 3.04008335, 3.74539008, 4.01431996,
       2.26547605, 2.66047323, 3.84238482, 2.17921165, 3.87859588,
       2.59899485, 1.94814647, 3.70801825, 2.11341037])

In [12]:
# 予測値：64の人は2.82ドル、63の人は2.97ドルのチップを払う
X_test

total_bill  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  \
64        17.59     3           0          1        0        1        0   
63        18.29     4           0          0        0        1        0   
55        19.49     2           0          1        0        0        1   
111        7.25     1           1          1        0        1        0   
225       16.27     2           1          0        1        0        0   
..          ...   ...         ...        ...      ...      ...      ...   
90        28.97     2           0          0        1        0        0   
101       15.38     2           1          0        1        0        0   
75        10.51     2           0          1        0        1        0   
4         24.59     4           1          1        0        0        1   
109       14.31     2           1          0        0        1        0   

     time_Dinner  
64             1  
63             1  
55             1  
111            1  
225            0  
..           ...  
90             1  
101            1  
75             1  
4              1  
109            1  

[74 rows x 8 columns]

In [13]:
# 実際のデータ
y_test

64     2.64
63     3.76
55     3.51
111    1.00
225    2.50
       ... 
90     3.00
101    3.00
75     1.25
4      3.61
109    4.00
Name: tip, Length: 74, dtype: float64

In [14]:
# モデルの評価(MSE)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred) # np.mean(np.square(t_test - y_pred))

0.955080898861715

# LOOCV

In [15]:
# データ準備
# total_billからtipを予測する
X = df['total_bill'].values.reshape(-1, 1)
y = df['tip']

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()

In [18]:
model = LinearRegression()
mse_list = []
for train_index, test_index in loo.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # モデル学習
    model.fit(X_train, y_train)
    # テストデータの予測
    y_pred = model.predict(X_test)
    # MSE
    mse = mean_squared_error(y_test, y_pred)
    mse_list.append(mse)

In [21]:
print(f"MSE(LOOCV):{np.mean(mse_list)}")
print(f"std:{np.std(mse_list)}")

MSE(LOOCV):1.0675673489857436
std:2.099794455177631


In [25]:
# cross_val_scoreを使えば２行で計算できる。
from sklearn.model_selection import cross_val_score
cv = LeaveOneOut()
scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error')
print(f"MSE(LOOCV):{-np.mean(scores)}")
print(f"std:{np.std(scores)}")

MSE(LOOCV):1.0675673489857436
std:2.099794455177631


# k-Fold CV

In [39]:
from sklearn.model_selection import KFold, RepeatedKFold
k = 5
n_repeats = 3
# cv = KFold(n_splits=k, shuffle=True, random_state=0)
cv = RepeatedKFold(n_splits=k, n_repeats=n_repeats, random_state=0)
model = LinearRegression()
mse_list = []
for train_index, test_index in cv.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    # モデル学習
    model.fit(X_train, y_train)
    # テストデータ予測
    y_pred = model.predict(X_test)
    # MSE
    mse = mean_squared_error(y_test, y_pred)
    mse_list.append(mse)

In [40]:
print(f"MSE({k}FoldCV): {np.mean(mse_list)}")
print(f"std: {np.std(mse_list)}")

MSE(5FoldCV): 1.0746387233165984
std: 0.26517178540898434


In [42]:
scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error')
print(f"MSE({k}FoldCV): {-np.mean(scores)}")
print(f"std: {np.std(scores)}")

MSE(5FoldCV): 1.0746387233165984
std: 0.26517178540898434


# Pipeline

## Pipeline + k-Fold

In [51]:
from sklearn.pipeline import Pipeline
pipline = Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])
cv = KFold(n_splits=5, shuffle=True, random_state=0)
scores = cross_val_score(pipline, X, y, scoring='neg_mean_squared_error', cv=cv)
scores

array([-0.82130906, -1.07458421, -1.08801239, -1.33238677, -1.084763  ])

In [61]:
## Pipelineなし
# 標準化　＋　線形回帰
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
model = LinearRegression()
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

In [62]:
y_pred

array([2.71486884, 2.78639251, 2.90900452, 1.65836207, 2.57999564,
       1.50509707, 2.74858715, 3.30136293, 2.77208778, 4.45800284,
       3.50060744, 3.49345507, 2.35520697, 2.24587793, 2.28879213,
       4.02375199, 1.77075641, 2.3480546 , 2.83645908, 3.2778623 ,
       3.98901192, 3.05511716, 2.55240794, 2.45431834, 2.29798803,
       2.59327861, 2.16004953, 3.96244599, 3.50162921, 2.5289073 ,
       2.42264357, 2.19274606, 2.49314547, 1.99963215, 2.78639251,
       2.28572683, 2.64743224, 1.97306622, 5.85577969, 2.55036441,
       1.79425705, 2.18763723, 2.52073317, 3.96755482, 2.22135553,
       2.65151931, 2.78128368, 3.12255376, 2.66173698, 3.66409011,
       4.2567148 , 2.74552185, 3.01118119, 5.83943142, 1.89847725,
       2.14676656, 3.97572896, 3.03161652, 2.37462053, 2.21113786,
       3.70496078, 2.53299437, 3.07963956, 3.47199797, 3.99718606,
       2.5043849 , 2.60043097, 4.2720413 , 1.97306622, 3.87763935,
       2.4890584 , 1.99145802, 3.43010554, 2.37972937])

In [58]:
## Pipelineあり
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
pipeline = Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])
pipeline.fit(X_train, y_train)
y_pred_p = pipeline.predict(X_test)
y_pred_p

array([2.71486884, 2.78639251, 2.90900452, 1.65836207, 2.57999564,
       1.50509707, 2.74858715, 3.30136293, 2.77208778, 4.45800284,
       3.50060744, 3.49345507, 2.35520697, 2.24587793, 2.28879213,
       4.02375199, 1.77075641, 2.3480546 , 2.83645908, 3.2778623 ,
       3.98901192, 3.05511716, 2.55240794, 2.45431834, 2.29798803,
       2.59327861, 2.16004953, 3.96244599, 3.50162921, 2.5289073 ,
       2.42264357, 2.19274606, 2.49314547, 1.99963215, 2.78639251,
       2.28572683, 2.64743224, 1.97306622, 5.85577969, 2.55036441,
       1.79425705, 2.18763723, 2.52073317, 3.96755482, 2.22135553,
       2.65151931, 2.78128368, 3.12255376, 2.66173698, 3.66409011,
       4.2567148 , 2.74552185, 3.01118119, 5.83943142, 1.89847725,
       2.14676656, 3.97572896, 3.03161652, 2.37462053, 2.21113786,
       3.70496078, 2.53299437, 3.07963956, 3.47199797, 3.99718606,
       2.5043849 , 2.60043097, 4.2720413 , 1.97306622, 3.87763935,
       2.4890584 , 1.99145802, 3.43010554, 2.37972937])